include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

formatter:
  trailing_commas: preserve

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_final_parameters
    - avoid_implementing_value_types
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - deprecated_member_use_from_same_package
    - directives_ordering
    - document_ignores
    - eol_at_end_of_file
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - matching_super_parameters
    - missing_code_block_language_in_doc_comment
    - no_literal_bool_comparisons
    - no_runtimeType_toString
    - no_self_assignments
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_mixin
    - prefer_single_quotes
    - prefer_void_to_null
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_async
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unreachable_from_main
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_null_aware_elements
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - use_truncating_division

dcm:
  metrics:
    # Function-level
    cyclomatic-complexity: 15
    source-lines-of-code: 60
    maximum-nesting-level: 5
    number-of-parameters: 6
    # Flutter specific
    number-of-used-widgets: 20
    widgets-nesting-level: 8
    # Class-level
    coupling-between-object-classes: 20
    depth-of-inheritance-tree: 5
    number-of-implemented-interfaces: 3
    number-of-methods: 10
    weighted-methods-per-class: 45
    # File-level
    number-of-external-imports: 6
    number-of-imports: 15
  rules:
    # Common
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-named-imports
    - avoid-dynamic
    - avoid-global-state
    - avoid-late-keyword:
        allow-initialized: true
        ignored-types:
          - AnimationController
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion:
        skip-checked-fields: true
    - avoid-redundant-async
    - avoid-self-compare
    - avoid-substring
    - avoid-throw-in-catch-block
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - binary-expression-operand-order
    - member-ordering
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-magic-number:
        allow-only-once: true
        ignore-instances: true
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions:
        ignore-nested: true
    - prefer-correct-test-file-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-match-file-name
    - prefer-moving-to-variable
    # Flutter
    - always-remove-listener
    - avoid-expanded-as-spacer
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-unnecessary-stateful-widgets
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-correct-edge-insets-constructor
    - prefer-define-hero-tag
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-text-rich
    - use-setstate-synchronously
    # Bloc
    - avoid-bloc-public-fields
    - avoid-bloc-public-methods
    - avoid-cubits
    - avoid-duplicate-bloc-event-handlers
    - avoid-empty-build-when
    - avoid-existing-instances-in-bloc-provider
    - avoid-instantiating-in-bloc-value-provider
    - avoid-passing-bloc-to-bloc
    - avoid-passing-build-context-to-blocs
    - avoid-returning-value-from-cubit-methods
    - check-is-not-closed-after-async-gap
    - emit-new-bloc-state-instances
    - handle-bloc-event-subclasses
    - prefer-bloc-event-suffix
    - prefer-bloc-extensions
    - prefer-bloc-state-suffix
    - prefer-correct-bloc-provider
    - prefer-immutable-bloc-events
    - prefer-immutable-bloc-state
    - prefer-multi-bloc-provider
    - prefer-sealed-bloc-events
    - prefer-sealed-bloc-state
