import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:thoughts/core/di/di.config.dart';

/// Shared service locator instance.
final getIt = GetIt.instance;

/// Registers all dependency injection bindings generated by `injectable`.
@injectableInit
void configureDependencies() => getIt.init();
